### ISSUE TITLE
IPv6 support for gateway.ipfs.io

### ISSUE THREAD

**Issue by kyledrake** [ipfs/infrastructure#124] opened 2015-11-24 05:57 UTC
Low-ish priority, but it shouldn't be too hard to setup.

I just enabled IPv6 on my router and was amazed to discover that my browser just auto-uses IPv6 by default without even telling me it was enabled. I had to install a plugin to even see if it was using 6, it's that transparent to end users now. Pretty cool.

**Comment by jbenet** [comment] 2015-11-30 08:59
We should be able to add ipv6 support: https://www.digitalocean.com/community/tutorials/how-to-enable-ipv6-for-digitalocean-droplets

**Comment by lgierth** [comment] 2015-12-10 01:59
duplicate of #88

**Closed by lgierth** 2015-12-10 01:59 UTC
